AWSTemplateFormatVersion: '2010-09-09'

Resources:
  VPC:
    Type: AWS::EC2::VPC
    Properties:
      CidrBlock: 10.0.0.0/16
      EnableDnsHostnames: true
      EnableDnsSupport: true
      Tags:
        - Key: Name
          Value: DayDreams-VPC

  InternetGateway:
    Type: AWS::EC2::InternetGateway

  VPCGatewayAttachment:
    Type: AWS::EC2::VPCGatewayAttachment
    Properties:
      VpcId: !Ref VPC
      InternetGatewayId: !Ref InternetGateway

  VPNConnection:
    Type: AWS::EC2::VPNConnection
    Properties:
      CustomerGatewayId: <insert_customer_gateway_id>
      VpnGatewayId: !Ref VPCGatewayAttachment
      Type: ipsec.1
      Tags:
        - Key: Name
          Value: DayDreams-VPNConnection

  VPNConnectionRoute:
    Type: AWS::EC2::VPNConnectionRoute
    Properties:
      DestinationCidrBlock: 0.0.0.0/0
      VpnConnectionId: !Ref VPNConnection

  S3Bucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: daydreams-storage-bucket
      AccessControl: Private
      Tags:
        - Key: Name
          Value: DayDreams-StorageBucket

  EC2Instance:
    Type: AWS::EC2::Instance
    Properties:
      ImageId: <insert_windows_11_ami_id>
      InstanceType: <insert_instance_type>
      KeyName: <insert_key_pair_name>
      SecurityGroupIds:
        - <insert_security_group_id>
      SubnetId: <insert_subnet_id>

  FileServer:
    Type: AWS::EC2::Instance
    Properties:
      ImageId: <insert_windows_2016_ami_id>
      InstanceType: <insert_instance_type>
      KeyName: <insert_key_pair_name>
      SecurityGroupIds:
        - <insert_security_group_id>
      SubnetId: <insert_subnet_id>

  RDSInstance:
    Type: AWS::RDS::DBInstance
    Properties:
      AllocatedStorage: 256
      DBInstanceIdentifier: DayDreamsDB
      Engine: <insert_database_engine>
      EngineVersion: <insert_database_version>
      MasterUsername: <insert_master_username>
      MasterUserPassword: <insert_master_password>
      VPCSecurityGroups:
        - <insert_security_group_id>

Outputs:
  VPNEndpoint:
    Value: !GetAtt VPNConnection.VpnGatewayId
    Description: VPN Endpoint for secure access

  StorageBucket:
    Value: !Ref S3Bucket
    Description: S3 Bucket for block storage

  EC2InstancePublicIP:
    Value: !GetAtt EC2Instance.PublicIp
    Description: Public IP of EC2 instance

  FileServerPublicIP:
    Value: !GetAtt FileServer.PublicIp
    Description: Public IP of File Server

  RDSInstanceEndpoint:
    Value: !GetAtt RDSInstance.Endpoint.Address
    Description: Endpoint of RDS instance
